export const actionTypes = {
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
  GET_EMPLOYEE: "GET_EMPLOYEE",
  GET_EMPLOYEELIST: "GET_EMPLOYEELIST",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_GET: "USER_GET",
};
